#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

separator () {
	echo "=> $1"
}
relink () {
	if [ -L "$2" ]; then
		# Remove existing symlink
		unlink "$2" 2> /dev/null
	fi
	if [ -f "$2" ]; then
		# Backup existing file
		rm "$2.bak" 2> /dev/null
		mv "$2" "$2.bak"
	fi

	ln -s "$1" "$2"
}

separator "Symlinking files in home directory.."
relink "$DIR/X11/xinitrc"    "$HOME/.xinitrc"
relink "$DIR/xterm/config"   "$HOME/.Xdefaults"
relink "$DIR/zsh/config"     "$HOME/.zshrc"
relink "$DIR/zsh/aliases"    "$HOME/.aliases"
relink "$DIR/i3/config"      "$HOME/.i3"
relink "$DIR/i3/status.conf" "$HOME/.i3status.conf"
relink "$DIR/git/config"     "$HOME/.gitconfig"
relink "$DIR/vim/config"     "$HOME/.vimrc"

separator "Installing FZF.."
"$DIR/fzf/install" --key-bindings --completion

separator "Symlinking X11 configs & scripts.."
sudo rm /etc/X11/xorg.conf.bak 2> /dev/null
sudo mv /etc/X11/xorg.conf /etc/X11/xorg.conf.bak 2> /dev/null
sudo cp "$DIR/X11/xorg.conf" /etc/X11/
sudo rm /etc/X11/xorg.conf.d/50-synaptics.conf 2> /dev/null
sudo cp "$DIR/X11/50-synaptics.conf" /etc/X11/xorg.conf.d/
sudo rm /etc/X11/Xsession.d/99x11-common_start 2> /dev/null
sudo cp "$DIR/X11/start" "/etc/X11/Xsession.d/99x11-common_start"
