# This file will be sourced by /etc/X11/Xsession.d/99x11-common_start

# Map Caps Lock to Escape
setxkbmap -option caps:escape &

# XTerm config
xrdb -merge "$HOME/.dotfiles/xterm/config"

# Disable touchpad while typing
# https://help.ubuntu.com/community/MacBookPro11-1/Saucy#Touchpad
syndaemon -d -i 1

exec i3
