# This file will be sourced by /etc/X11/Xsession.d/99x11-common_start

# Set keyboard layout and options
setxkbmap -layout us -variant mac -option '' \
	-option caps:escape # Map caps lock to escape

# XTerm config
xrdb -merge "$HOME/.dotfiles/xterm/config"

# Disable touchpad while typing
# https://help.ubuntu.com/community/MacBookPro11-1/Saucy#Touchpad
syndaemon -d -i 0.3

exec i3
